import * as core from '@actions/core'

export type Values = {
  [keyof: string]: unknown
}

export const anchor = '<!-- jmatsu/issue-metadata -->'

export const extractValues = (body: string): Values => {
  const fragment = body.split(anchor)[1]

  if (!fragment) {
    throw new Error('this comment is invalid because the fragment is broken.')
  }

  const start = fragment.indexOf('<!--') + '<!--'.length
  const end = fragment.lastIndexOf('-->')

  const valueContent = fragment.substring(start, end)

  return JSON.parse(valueContent)
}

export const buildCommentBody: (
  id: string,
  value: unknown,
  acc: Values
) => string = (id, value, acc) => {
  acc[id] = value

  return `This comment is generated by [jmatsu/issue-metadata](https://github.com/jmatsu/issue-metadata). Do not edit this comment directly.

${anchor}
<!--
${JSON.stringify(acc, null, 2)}
-->`
}
