name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: write-values
        uses: ./
        with:
          id: "foo"
          value: "baz"
          issue-number: ${{ github.event.pull_request.number || '1' }}
      - run: |
          echo "| context | key | value | " >> $GITHUB_STEP_SUMMARY
          echo "| :-- | :-- | :-- | " >> $GITHUB_STEP_SUMMARY
          echo "| write-values| foo | ${{ steps.write-values.outputs.value }} |" >> $GITHUB_STEP_SUMMARY
      - id: read-values
        uses: ./
        with:
          id: "foo"
          read-only: true
          issue-number: ${{ github.event.pull_request.number || '1' }}
      - run: |
          echo "| context | key | value | " >> $GITHUB_STEP_SUMMARY
          echo "| :-- | :-- | :-- | " >> $GITHUB_STEP_SUMMARY
          echo "| read-values| foo | ${{ steps.read-values.outputs.value }} |" >> $GITHUB_STEP_SUMMARY
      - id: read-values-for-missing
        uses: ./
        with:
          id: "bar"
          read-only: true
          issue-number: ${{ github.event.pull_request.number || '1' }}
      - run: |
          echo "| context | key | value | " >> $GITHUB_STEP_SUMMARY
          echo "| :-- | :-- | :-- | " >> $GITHUB_STEP_SUMMARY
          echo "| read-values-for-missing| bar | ${{ steps.read-values-for-missing.outputs.value }}|" >> $GITHUB_STEP_SUMMARY
